---
include:
  - board: nice_nano//zmk
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DOS_MACOS
    artifact-name: corne_left_macos
  - board: nice_nano//zmk
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DOS_MACOS
    artifact-name: corne_right_macos
  - board: nice_nano//zmk
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_left_linux
  - board: nice_nano//zmk
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right_linux
